//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrunchCraft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryAdjustements
    {
        public int Id { get; set; }
        public Nullable<int> fk_IdKindOfInventory { get; set; }
        public string KindOfAdjust { get; set; }
        public Nullable<decimal> Qty_Before { get; set; }
        public Nullable<decimal> Qty_After { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual KindOfInventory KindOfInventory { get; set; }
    }
}
