//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrunchCraft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder
    {
        public int Id { get; set; }
        public Nullable<int> fk_SKUInventorySKU { get; set; }
        public string Product { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual InventorySKU InventorySKU { get; set; }
    }
}
